## YAML Template.
minecraft:cactus[age=6]:
  Z: 0.2 
  Y: -0.5
  Yaw: 0
minecraft:cactus[age=7]:
  X: -0.2
  Y: -0.5
  Yaw: 90
minecraft:cactus[age=8]:
  Z: -0.2  
  Y: -0.5
  Yaw: 180
minecraft:cactus[age=9]:
  X: 0.2
  Y: -0.5
  Yaw: 270

